"""add user enrollment

Revision ID: 17b4d0170f0c
Revises: 6ac6879a4c86
Create Date: 2026-10-07 18:21:24.095412
"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision = '17b4d0170f0c'
down_revision = '6ac6879a4c86'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
