"""add user enrollment

Revision ID: 29d3b37679ea
Revises: 17b4d0170f0c
Create Date: 2026-10-07 18:24:36.093365
"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision = '29d3b37679ea'
down_revision = '17b4d0170f0c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_daily_rollups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('day', sa.String(length=10), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=True),
    sa.Column('class_id', sa.UUID(), nullable=True),
    sa.Column('active_students', sa.Integer(), nullable=False),
    sa.Column('sessions_started', sa.Integer(), nullable=False),
    sa.Column('questions_asked', sa.Integer(), nullable=False),
    sa.Column('answers_correct', sa.Integer(), nullable=False),
    sa.Column('answers_verified', sa.Integer(), nullable=False),
    sa.Column('avg_response_ms', sa.Float(), nullable=False),
    sa.Column('mode_counts', sa.JSON(), nullable=False),
    sa.Column('top_concepts', sa.JSON(), nullable=False),
    sa.Column('weak_concepts', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_daily_rollups_class_id'), 'analytics_daily_rollups', ['class_id'], unique=False)
    op.create_index(op.f('ix_analytics_daily_rollups_day'), 'analytics_daily_rollups', ['day'], unique=False)
    op.create_index(op.f('ix_analytics_daily_rollups_school_id'), 'analytics_daily_rollups', ['school_id'], unique=False)
    op.create_table('analytics_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=True),
    sa.Column('school_id', sa.UUID(), nullable=True),
    sa.Column('class_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=True),
    sa.Column('chapter_id', sa.UUID(), nullable=True),
    sa.Column('section_id', sa.UUID(), nullable=True),
    sa.Column('concept_key', sa.String(length=120), nullable=True),
    sa.Column('mode', sa.String(length=30), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('was_verified', sa.Boolean(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_events_class_id'), 'analytics_events', ['class_id'], unique=False)
    op.create_index(op.f('ix_analytics_events_concept_key'), 'analytics_events', ['concept_key'], unique=False)
    op.create_index(op.f('ix_analytics_events_event_type'), 'analytics_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_analytics_events_school_id'), 'analytics_events', ['school_id'], unique=False)
    op.create_index(op.f('ix_analytics_events_student_id'), 'analytics_events', ['student_id'], unique=False)
    op.create_index('ix_analytics_events_type_day', 'analytics_events', ['event_type', 'created_at'], unique=False)
    op.add_column('users', sa.Column('school_id', sa.UUID(), nullable=True))
    op.add_column('users', sa.Column('class_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_users_class_id'), 'users', ['class_id'], unique=False)
    op.create_index(op.f('ix_users_school_id'), 'users', ['school_id'], unique=False)
    op.create_foreign_key(None, 'users', 'classes', ['class_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'users', 'schools', ['school_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_school_id'), table_name='users')
    op.drop_index(op.f('ix_users_class_id'), table_name='users')
    op.drop_column('users', 'class_id')
    op.drop_column('users', 'school_id')
    op.drop_index('ix_analytics_events_type_day', table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_student_id'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_school_id'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_event_type'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_concept_key'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_class_id'), table_name='analytics_events')
    op.drop_table('analytics_events')
    op.drop_index(op.f('ix_analytics_daily_rollups_school_id'), table_name='analytics_daily_rollups')
    op.drop_index(op.f('ix_analytics_daily_rollups_day'), table_name='analytics_daily_rollups')
    op.drop_index(op.f('ix_analytics_daily_rollups_class_id'), table_name='analytics_daily_rollups')
    op.drop_table('analytics_daily_rollups')
    # ### end Alembic commands ###
