"""add class_id subject_id to concepts

Revision ID: 400c7ac8621c
Revises: 6898f6fbac3c
Create Date: 2026-10-08 07:11:24.932236
"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision = '400c7ac8621c'
down_revision = '6898f6fbac3c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
