"""add class_id subject_id to concepts

Revision ID: 6898f6fbac3c
Revises: b8025b6fab85
Create Date: 2026-10-08 06:34:29.731155
"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision = '6898f6fbac3c'
down_revision = 'b8025b6fab85'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
