"""add concept graph

Revision ID: 6ac6879a4c86
Revises: a44a503483d7
Create Date: 2026-10-06 05:45:00.976170
"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision = '6ac6879a4c86'
down_revision = 'a44a503483d7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concepts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('primary_section_id', sa.UUID(), nullable=True),
    sa.Column('learning_objectives', sa.JSON(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['primary_section_id'], ['sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_concepts_key'), 'concepts', ['key'], unique=True)
    op.create_index(op.f('ix_concepts_primary_section_id'), 'concepts', ['primary_section_id'], unique=False)
    op.create_table('concept_misconceptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('concept_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('remedy', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_concept_misconceptions_concept_id'), 'concept_misconceptions', ['concept_id'], unique=False)
    op.create_table('concept_prerequisites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('concept_id', sa.UUID(), nullable=False),
    sa.Column('prerequisite_id', sa.UUID(), nullable=False),
    sa.Column('strength', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ),
    sa.ForeignKeyConstraint(['prerequisite_id'], ['concepts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('concept_id', 'prerequisite_id', name='uq_concept_prereq')
    )
    op.create_index(op.f('ix_concept_prerequisites_concept_id'), 'concept_prerequisites', ['concept_id'], unique=False)
    op.create_index(op.f('ix_concept_prerequisites_prerequisite_id'), 'concept_prerequisites', ['prerequisite_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_concept_prerequisites_prerequisite_id'), table_name='concept_prerequisites')
    op.drop_index(op.f('ix_concept_prerequisites_concept_id'), table_name='concept_prerequisites')
    op.drop_table('concept_prerequisites')
    op.drop_index(op.f('ix_concept_misconceptions_concept_id'), table_name='concept_misconceptions')
    op.drop_table('concept_misconceptions')
    op.drop_index(op.f('ix_concepts_primary_section_id'), table_name='concepts')
    op.drop_index(op.f('ix_concepts_key'), table_name='concepts')
    op.drop_table('concepts')
    # ### end Alembic commands ###
