"""add class_id subject_id to concepts

Revision ID: 8fd08d2adb01
Revises: 400c7ac8621c
Create Date: 2026-10-08 07:15:20.424962
"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision = '8fd08d2adb01'
down_revision = '400c7ac8621c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('concept_misconceptions_concept_id_fkey', 'concept_misconceptions', type_='foreignkey')
    op.create_foreign_key(None, 'concept_misconceptions', 'concepts', ['concept_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('concept_prerequisites_prerequisite_id_fkey', 'concept_prerequisites', type_='foreignkey')
    op.drop_constraint('concept_prerequisites_concept_id_fkey', 'concept_prerequisites', type_='foreignkey')
    op.create_foreign_key(None, 'concept_prerequisites', 'concepts', ['prerequisite_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'concept_prerequisites', 'concepts', ['concept_id'], ['id'], ondelete='CASCADE')
    op.add_column('concepts', sa.Column('class_id', sa.UUID(), nullable=True))
    op.add_column('concepts', sa.Column('subject_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_concepts_class_id'), 'concepts', ['class_id'], unique=False)
    op.create_index(op.f('ix_concepts_subject_id'), 'concepts', ['subject_id'], unique=False)
    op.drop_constraint('concepts_primary_section_id_fkey', 'concepts', type_='foreignkey')
    op.create_foreign_key(None, 'concepts', 'classes', ['class_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'concepts', 'sections', ['primary_section_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'concepts', 'subjects', ['subject_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'concepts', type_='foreignkey')
    op.drop_constraint(None, 'concepts', type_='foreignkey')
    op.drop_constraint(None, 'concepts', type_='foreignkey')
    op.create_foreign_key('concepts_primary_section_id_fkey', 'concepts', 'sections', ['primary_section_id'], ['id'])
    op.drop_index(op.f('ix_concepts_subject_id'), table_name='concepts')
    op.drop_index(op.f('ix_concepts_class_id'), table_name='concepts')
    op.drop_column('concepts', 'subject_id')
    op.drop_column('concepts', 'class_id')
    op.drop_constraint(None, 'concept_prerequisites', type_='foreignkey')
    op.drop_constraint(None, 'concept_prerequisites', type_='foreignkey')
    op.create_foreign_key('concept_prerequisites_concept_id_fkey', 'concept_prerequisites', 'concepts', ['concept_id'], ['id'])
    op.create_foreign_key('concept_prerequisites_prerequisite_id_fkey', 'concept_prerequisites', 'concepts', ['prerequisite_id'], ['id'])
    op.drop_constraint(None, 'concept_misconceptions', type_='foreignkey')
    op.create_foreign_key('concept_misconceptions_concept_id_fkey', 'concept_misconceptions', 'concepts', ['concept_id'], ['id'])
    # ### end Alembic commands ###
