"""add concept graph

Revision ID: a44a503483d7
Revises: 699052cc7599
Create Date: 2026-10-06 04:42:39.799847
"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision = 'a44a503483d7'
down_revision = 'ff03280a4e54'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
