"""add class_id subject_id to concepts

Revision ID: b8025b6fab85
Revises: c24c29f9fad4
Create Date: 2026-10-08 06:34:09.510873
"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision = 'b8025b6fab85'
down_revision = 'c24c29f9fad4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
