"""initial schema

Revision ID: ff03280a4e54
Revises: 
Create Date: 2026-10-05 11:54:35.260891
"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision = 'ff03280a4e54'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
